### ISSUE TITLE
Testnet Block Explorers returning "undefined" during block height command

### ISSUE THREAD

**Issue by arca-music** [xunga/lisk-cute-assistant#2]
Testnet BE URLs in `/src/config_sample.js_testnet` for API blocked by nginx and will not pull info for block height check. Bot returns `undefined` for those lines.

**Comment by xunga** [comment]
@NightAngel0589 Thanks a lot for opening this issue. It will be fixed into the next release, together with new improvements.

In the meanwhile, if you know any other public node where we can check the block heights, feel free to post it here. :)

**Comment by xunga** [comment]
For anyone who wants to pick this issue, here is a guideline of what it should be done:

- Run the bot in testnet and take a note of which nodes are not properly working on the blockheights check
- Find new testnet nodes 
- Replace it in the configuration
- Make a PR

**Comment by xunga** [comment]
Fixed with PR #15
